spring:
  datasource:
        url: jdbc:mysql://localhost:3306/ai?serverTimezone=GMT
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
  jpa:
    show-sql: true
localPath:
  image: E:\upload\images
  speech: E:\upload\speeches