spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_rubbish
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
localPath:
  image: /root/upload/images
  speech: /root/upload/speeches