spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ai?serverTimezone=GMT
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
    url: jdbc:mysql://10.167.234.83:3306/ai?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
localPath:
  image: /root/upload/images
  speech: /root/upload/speeches